/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Change {
  value: string
  added: boolean
  removed: boolean
  count: number
}

export declare function diffChars(before: string, after: string): Array<Change>

export declare function diffLines(before: string, after: string): Array<Change>

export declare function diffWords(before: string, after: string): Array<Change>

export declare function unifiedDiff(before: string, after: string): string
